name: 📔 Documentation
description: Report an issue related to documentation
title: "Docs: "
labels:
    - "kind/docs"
    - "support/needs-triage"

body:
    - type: markdown
      attributes:
          value: |
              👋🏽 Thanks for reporting this issue to us, here is a preliminary checklist
              
              Here is a preliminary checklist:

              - I understand that all communication must be in English
              - I read the [Documentation](https://engineering.foret.ag)
              - I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
              - I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
              - I searched the issues and discussions but couldn't find anything similar

    - type: textarea
      id: problem
      attributes:
          label: Problem
          description: Describe your current issue with the existing documentation
          placeholder: I couldn't find docs for...
      validations:
          required: true

    - type: dropdown
      id: contribution
      attributes:
          label: Contribution
          description: Would you be willing to submit a PR?
          multiple: false
          options:
              - "Yes, I will work on a PR"
              - "No, I cannot contribute further"
      validations:
          required: true

    - type: input
      id: keywords
      attributes:
          label: Keywords
          description:
              What keywords did you use when trying to find documentation?
              List them here so people in the future can find this one more easily.
          placeholder: i.e. integration, graphql, grpc
      validations:
          required: false
