name: 🐞 Bug Report
description: File a bug report here
title: "Bug: "
labels:
    - "kind/bug"
    - "kind/needs-triage"

body:
    - type: markdown
      attributes:
          value: |
              Some general tips:

              - Is this really a problem?
              - Is this a problem here?

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Environment are you on i.e. Local, Bare Metal or Cloud
          placeholder: i.e. Local - RockyLinux 9 on ARM64 with 8 GB RAM, 4 vCPU
              feel free to add any other related hardware / software specs and if the project has differet editions or plans (OSS, Cloud, and Enterprise) be sure to add that
      validations:
          required: true

    - type: input
      id: keywords
      attributes:
          label: Keywords
          description:
              What keywords did you use when trying to find an existing bug report?
              List them here so people in the future can find this one more easily.
          placeholder: i.e. database, connection, error 2025
      validations:
          required: false

    - type: textarea
      id: background
      attributes:
          label: Background
          description: Explain your problem with the expected behavior.
          placeholder: Add as much detail in here as possible explaining the problem, the background context (what you are trying to achieve) etc.
      validations:
          required: true

    - type: textarea
      id: current-behavior
      attributes:
          label: Current behavior
          description: A concise description of what you expected to happen.
          placeholder: Again, add as much detail as possible outlining what goes wrong including any edge cases.
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              Example -
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: true

    - type: textarea
      id: screenshot
      attributes:
          label: Screenshot or Screencast
          description: Providing relevant Screenshots/ Screencasts would help us to debug the issue quickly.
          placeholder: Link or paste your media
      validations:
          required: false

    - type: textarea
      id: logs
      attributes:
          label: Logs and traces
          description: Provide any traces or logs that could help here
          placeholder: Add any content from your ui, console or terminal where necessary
      validations:
          required: false

    - type: textarea
      id: solution
      attributes:
          label: Solution
          description: Any possible solutions or releated information
      validations:
          required: false

    - type: textarea
      id: debugging
      attributes:
          label: Debugging
          description: Can you identify the location in the source code where the problem exists
          placeholder: Add as many references as you can i.e
              L22:49 on project/example.rs calls function_with_error(value);
              L72:88 on project/main.rs calls nested_function(error);
      validations:
          required: false

    - type: dropdown
      attributes:
          label: Contribution
          description: If the bug is confirmed, would you be willing to submit a PR?
          multiple: false
          options:
              - "Yes"
              - "No"
      validations:
          required: true
