name: 🐞 Bug Report
description: File a bug report here
title: "Bug: "
labels: ["kind/bug", "kind/needs-triage"]

body:
    - type: textarea
      id: current-behavior
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Contribution
          description: If the bug is confirmed, would you be willing to submit a PR?
          options:
              - label: Yes
              - label: No
                required: false
