name: 🐞 Bug Report
description: File a bug report here
title: "Bug: "
labels:
    - "kind/bug"
    - "kind/needs-triage"

body:
    - type: markdown
      attributes:
          value: |
              Some general tips:

              - Is this really a problem?
              - Is this a problem here?

    - type: textarea
      id: current-behavior
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true
